"""Constantes visuales compartidas por los componentes de la interfaz."""

COLOR_PRIMARY = "#4a6da7"
COLOR_PRIMARY_SOFT = "#e8edf6"
COLOR_ACCENT = "#5b3c88"
COLOR_BACKGROUND = "#f4f5f9"
COLOR_CARD = "#ffffff"
COLOR_BORDER = "#d8dce6"
COLOR_DISABLED = "#c9cedb"
COLOR_DISABLED_TEXT = "#f4f5f9"
COLOR_MUTED = "#6b7280"
COLOR_INFO = "#3f4a5f"
COLOR_SUCCESS = "#2f7d4f"
COLOR_WARNING = "#a86400"
COLOR_ERROR = "#b3261e"
